### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by flkas** [wldn/Nginx-Vhost-CRUD-Operation#1]
The Readme has an link issue in line

>  Assumption(s) : You have set your basic Nginx virtual host / server blocks. If you haven't set it yet, check to this link :
 How to set up nginx virtual host on Ubuntu 14.04
>

It directs to setup apache virtual hosts. 
The correct link would be : 

[ How to set up nginx virtual host on Ubuntu 16.04
](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04)

**Comment by wildan3105** [comment]
Ah I see. Thank you very much for the correction :+1:
